config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items do
    member do
      patch :complete
    end
  end
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy]
  def index
    @items = Item.where(user_id: current_user.id).order("created_at DESC")
  end

  def show
  end

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      redirect_to items_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  def complete
    @item = Item.find(params[:id])
    @item.update_attribute(:completed_at, Time.now)
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :description)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <%= f.input :title, label: "Item Title" %>
  <%= f.input :description %>
  <%= f.button :submit, class:"btn btn-primary" %>
  <%= link_to "Back", @item, class:"btn btn-danger"  %>
<% end %>

app/views/items/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit New Todo Item</h1>
  <%= render 'form' %>
</div>

app/views/items/index.html.erb
  <div class="col-md-10 col-md-offset-1">
    <% @items.each do |item| %>
      <div class="index-wrapper">
        <% if item.completed? %>

<!-- For Completed Items-->
          <div class="row item">
            <div class="col-md-2">
              <p><%= link_to complete_item_path(item), method: :patch do %></p>
                <i class="fa fa-check fa-lg"></i>
        <% end %>
            </div>

            <div class="col-md-2">
              <p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
                <i class="fa fa-trash fa-lg"></i>
              <% end %>
            </div>

            <div class="col-md-8">
              <h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h2>
              <p style="opacity: 0.5;" class="item-sub-title item-desc"><%= item.description %></p>
              <p style="opacity: 0.5;" class="time-created-at item-sub-title">Completed <%= time_ago_in_words(item.completed_at) %> ago</p>
            </div>
          </div>
        <% else %>
<!-- For Items NOT Completed -->

        <div class="row item">

          <div class="col-md-2">
            <p><%= link_to complete_item_path(item), method: :patch do %></p>
              <i class="fa fa-check fa-lg"></i>
            <% end %>
          </div>

          <div class="col-md-8">
            <h2 class="item-title"><%= link_to item.title, item %></h2>
            <p class="item-sub-title item-desc"><%= item.description %></p>
            <p style="opacity: 0.5;" class="time-created-at item-sub-title">Created <%= time_ago_in_words(item.created_at) %> ago</p>
          </div>

          <div class="col-md-2">
            <p><%= link_to item, method: :delete, data: { confirm: "Are you sure?" } do %></p>
              <i class="fa fa-trash fa-lg"></i>
            <% end %>
          </div>
        </div>

      <% end %>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>New Todo Item</h1>
  <%= render 'form' %>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <h2><%= @item.title %></h2>
      <p><%= @item.description %> </p>
    </div>
    <div class="col-md-4 col-md-offset-4">
      <%= link_to "Back", items_path  %>
      <%= link_to "Edit", edit_item_path(@item) %>
      <%= link_to "Delete", item_path(@item), method: :delete, data: {confirm: "Are you sure"}  %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hiptime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1536060316316-2466bda904f1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80);">
  <div class="container">
    <h1>Hiptime <strong>Mange your</strong> todo <strong>list</strong>!</h1>
    <p>Manage your todo list in a easier way from anywhere in the world</p>
    <% if user_signed_in? %>
      <%= link_to "Get Started", items_path, class:"btn btn-primary"  %>
    <!-- <a class="btn btn-primary" href= >Sign Up Now!!</a> -->
    <% else %>
      <%= link_to "Sign Up Now", new_user_registration_path, class:"btn btn-danger"  %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "blob.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "All Items", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Item", new_item_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "boy.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>

        </li>
      <% end %>
    </ul>
  </div>
</div>